// ===== GAME DATA =====
// Story 1 = Ocean (White Reef Mystery)
// Story 2 = Garden (Silent Garden Mystery)
// Garden NPCs from files: butterfly, daisy, mushroom, oak_tree, robin

const GameData = {

  stories: {
    ocean: {
      id: 'ocean',
      title: 'White Reef Mystery',
      location: 'Hashima Island, Japan',
      ambient: 'story1_ambient',
      background: 'assests/bg/story 1.png',
      levels: 5,
      summary: 'The ocean is dying. Rising heat bleached the coral. Alien machines descended and extracted something from the seafloor — accelerating what human pollution had already started.',
      finalWords: '"The ocean is the heart of our world. And it is breaking. We must protect it — not just from the aliens, but from ourselves. Because the ocean remembers everything."',
      caseName: 'White Reef Mystery',
      introTitle: 'Story I: White Reef Mystery',
    },
    garden: {
      id: 'garden',
      title: 'Silent Garden Mystery',
      location: 'Pripyat, Ukraine',
      ambient: 'story2_ambient',
      background: 'assests/bg/story 2.jpeg',
      levels: 5,
      summary: 'The garden fell silent — not because of one thing, but because of many things. Humans replaced native flowers with ornamentals that fed no one. Pollinators starved. Insects disappeared. Birds had nothing to eat. The soil died. And then the aliens came. They drained the land\'s energy. They accelerated the collapse. They brought the silence. The garden is dead — and the silence is our responsibility.',
      finalWords: '"The silence is never peaceful. It is the sound of something dying. The garden remembers. The daisy remembers. The butterfly remembers. The robin remembers. The oak tree remembers. And now, so do I."',
      caseName: 'Silent Garden Mystery',
      introTitle: 'Story II: Silent Garden Mystery',
    },
  },

  // ── SPRITE SHEET DEFINITIONS ─────────────────────────────────────────────
  // All measurements confirmed from actual files
  hassel: {
    // Single-frame statics (255x474 each)
    frameW: 255, frameH: 474,
    sheets: {
      walk:          { src: 'assests/Hazzel/walking.png',         frames: 5, fps: 10, w: 255, h: 474 },
      run:           { src: 'assests/Hazzel/running.png',         frames: 7, fps: 12, w: 159, h: 414 },
      echo:          { src: 'assests/Hazzel/echo_sight.png',      frames: 1, fps: 4,  w: 255, h: 474 },
      lookaround:    { src: 'assests/Hazzel/looking_around.png',  frames: 1, fps: 4,  w: 255, h: 474 },
      idle_front:    { src: 'assests/Hazzel/idle_front.png',      frames: 1, fps: 1,  w: 255, h: 474 },
      idle_side:     { src: 'assests/Hazzel/idle_side.png',       frames: 1, fps: 1,  w: 255, h: 474 },
      idle_back:     { src: 'assests/Hazzel/idle_back.png',       frames: 1, fps: 1,  w: 255, h: 474 },
      idle_3q:       { src: 'assests/Hazzel/idle_threequarter.png',frames:1, fps: 1,  w: 255, h: 474 },
      thinking:      { src: 'assests/Hazzel/thinking.png',        frames: 1, fps: 1,  w: 255, h: 474 },
      write_sit:     { src: 'assests/Hazzel/write_siting.png',    frames: 1, fps: 1,  w: 255, h: 474 },
      write_stand:   { src: 'assests/Hazzel/write_standing.png',  frames: 1, fps: 1,  w: 255, h: 474 },
      happy:         { src: 'assests/Hazzel/happy.png',           frames: 1, fps: 1,  w: 255, h: 474 },
      sad:           { src: 'assests/Hazzel/sad.png',             frames: 1, fps: 1,  w: 255, h: 474 },
      worried:       { src: 'assests/Hazzel/worried.png',         frames: 1, fps: 1,  w: 255, h: 474 },
      determined:    { src: 'assests/Hazzel/determined.png',      frames: 1, fps: 1,  w: 255, h: 474 },
      shock:         { src: 'assests/Hazzel/shock.png',           frames: 1, fps: 1,  w: 255, h: 474 },
      smile:         { src: 'assests/Hazzel/smile.png',           frames: 1, fps: 1,  w: 255, h: 474 },
    },
  },

  // ── NPC SPRITE SHEETS (frame widths verified by alpha-edge detection) ──────
  npcSheets: {
    // Ocean
    clownfish:  { mov: { src:'assests/NPC/Story 1/clownfish_movement.png', frames:6, fw:384, fh:252 },
                  static: { src:'assests/NPC/Story 1/clownfish.png', w:339, h:252 } },
    sea_turtle: { mov: { src:'assests/NPC/Story 1/turtle_movement.png',    frames:4, fw:497, fh:255 },
                  static: { src:'assests/NPC/Story 1/turtle.png',   w:372, h:255 } },
    octopus:    { mov: { src:'assests/NPC/Story 1/octopus_movement.png',   frames:5, fw:372, fh:354 },
                  static: { src:'assests/NPC/Story 1/octopus.png',  w:399, h:336 } },
    coral:      { mov: { src:'assests/NPC/Story 1/coral_movement.png',     frames:4, fw:483, fh:462 },
                  static: { src:'assests/NPC/Story 1/coral.png',    w:528, h:456 } },
    whale:      { mov: { src:'assests/NPC/Story 1/whale_movement.png',     frames:5, fw:528, fh:306 },
                  static: { src:'assests/NPC/Story 1/whale.png',    w:513, h:306 } },
    // Garden
    butterfly:  { mov: { src:'assests/NPC/Story 2/butterfly_movement.png', frames:7, fw:297, fh:282 },
                  static: { src:'assests/NPC/Story 2/butterfly.png',w:297, h:282 } },
    daisy:      { mov: { src:'assests/NPC/Story 2/daisy_movement.png',     frames:5, fw:297, fh:384 },
                  static: { src:'assests/NPC/Story 2/daisy.png',    w:297, h:384 } },
    mushroom:   { mov: { src:'assests/NPC/Story 2/mushroom_movement.png',  frames:5, fw:321, fh:363 },
                  static: { src:'assests/NPC/Story 2/mushroom.png', w:321, h:363 } },
    oak_tree:   { mov: { src:'assests/NPC/Story 2/oak_tree_movement.png',  frames:3, fw:720, fh:576 },
                  static: { src:'assests/NPC/Story 2/oak_tree.png', w:642, h:576 } },
    robin:      { mov: { src:'assests/NPC/Story 2/robin_movement.png',     frames:7, fw:354, fh:344 },
                  static: { src:'assests/NPC/Story 2/robin.png',    w:354, h:344 } },
  },

  // ── NPC GAMEPLAY DATA ─────────────────────────────────────────────────────
  // movType: 'loop'   = swims across entire screen, loops at edges
  //          'wander' = elliptical patrol around home point
  //          'static' = does not move
  // solid: true = Hassel collides with it
  npcs: {
    ocean: [
      {
        id: 'clownfish', name: 'Clownfish',
        sheetKey: 'clownfish',
        movType: 'loop', loopDir: 1,
        // Swims freely through mid-to-lower water
        yMin: 0.25, yMax: 0.72,
        x: -200, y: 0, patrolRadius: 0, speed: 1.8,
        solid: true,
        // Multi-speaker dialogue: { speaker, side, text, hassleExpr }
        dialogue: [
          { side:'hassel', speaker:'Hassel', hassleExpr:'sad',
            text: "You're the only one left, aren't you? The last of your kind in this reef." },
          { side:'npc', speaker:'Clownfish', hassleExpr:'sad',
            text: "I used to weave through the coral branches. Hundreds of us. We danced together. Now I dance alone. The coral turned white. The water grew warm. I saw the green light from the sky." },
          { side:'npc', speaker:'Clownfish', hassleExpr:'sad',
            text: "They took something. I don't know what. I only know my home is gone. My family is gone. I am the last one." },
          { side:'hassel', speaker:'Hassel', hassleExpr:'worried',
            text: "I'm so sorry. I can't bring them back. But I can remember them. I can tell their story. What was your home like?" },
          { side:'npc', speaker:'Clownfish', hassleExpr:'idle',
            text: "It was colorful. Vibrant. Full of life. We hid in the anemones. We played in the currents. We were happy. I don't remember the last time I was happy." },
          { side:'hassel', speaker:'Hassel', hassleExpr:'determined',
            text: "Tell them. Tell the world what happened here. So they don't forget what was lost." },
          { side:'npc', speaker:'Clownfish', hassleExpr:'idle',
            text: "Tell them. Tell the world what happened here. So they don't forget us." },
          { side:'thought', speaker:'Hassel', hassleExpr:'thinking',
            text: "A single fish remembers an entire reef. Its memory holds the color, the life, the joy of thousands. The ocean is full of ghosts." },
        ],
        clue: { title: 'Clownfish Testimony', text: 'Coral Bleaching + Alien Ship in Sky' },
        expression: 'sad',
      },
      {
        id: 'sea_turtle', name: 'Sea Turtle',
        sheetKey: 'sea_turtle',
        movType: 'loop', loopDir: -1,
        useStaticSprite: true,
        yMin: 0.50, yMax: 0.78,
        x: 0, y: 0, patrolRadius: 0, speed: 0.8,
        solid: true,
        dialogue: [
          { side:'hassel', speaker:'Hassel', hassleExpr:'idle',
            text: "You've seen a hundred years of this ocean. What do you remember?" },
          { side:'npc', speaker:'Sea Turtle', hassleExpr:'idle',
            text: "I remember when the water was cool. I remember when the reef sang. Fish of every color. Whales that called to each other across the ocean. We traveled together. Now I travel alone." },
          { side:'npc', speaker:'Sea Turtle', hassleExpr:'idle',
            text: "The water is warm. The reef is silent. The whales call, but no one answers." },
          { side:'hassel', speaker:'Hassel', hassleExpr:'sad',
            text: "You've watched it all die, haven't you? Year by year. Season by season." },
          { side:'npc', speaker:'Sea Turtle', hassleExpr:'idle',
            text: "It was not sudden. It was slow. The heat increased one degree at a time. The fish left one species at a time. The coral bleached one patch at a time." },
          { side:'npc', speaker:'Sea Turtle', hassleExpr:'idle',
            text: "And then the green light came. They descended into the depths. They took something. After that, the reef began to die faster. I felt the ocean cry." },
          { side:'hassel', speaker:'Hassel', hassleExpr:'determined',
            text: "I will carry it too. I will tell the world what you remember." },
          { side:'npc', speaker:'Sea Turtle', hassleExpr:'idle',
            text: "Thank you. The ocean remembers. And now, so do you." },
          { side:'thought', speaker:'Hassel', hassleExpr:'thinking',
            text: "A hundred years of memory in one ancient creature. The warming was slow — too slow to notice. But the turtle noticed. It noticed everything." },
        ],
        clue: { title: 'Sea Turtle Testimony', text: 'Long-Term Ocean Warming + Alien Ship Descending' },
        expression: 'determined',
      },
      {
        id: 'octopus', name: 'Octopus',
        sheetKey: 'octopus',
        movType: 'wander',
        x: 310, y: 0,
        useFloorY: true,
        patrolRadius: 55, speed: 0.5,
        solid: true,
        dialogue: [
          { side:'hassel', speaker:'Hassel', hassleExpr:'idle',
            text: "I'm not here to hurt you. I'm here to understand. Can you show me what you saw?" },
          { side:'npc', speaker:'Octopus', hassleExpr:'worried',
            text: "I remember the sound. A deep, grinding sound from the ocean floor. Like something was being ripped from the earth. I hid. I watched." },
          { side:'npc', speaker:'Octopus', hassleExpr:'worried',
            text: "Machines descended — cold, metallic, glowing green. They took something. The water grew warm. The coral screamed." },
          { side:'hassel', speaker:'Hassel', hassleExpr:'shock',
            text: "The coral... screamed?" },
          { side:'npc', speaker:'Octopus', hassleExpr:'worried',
            text: "Not with a voice. But I felt it. A vibration. A cry of pain. When they took what they wanted, the reef began to die. The fish left. The silence came." },
          { side:'npc', speaker:'Octopus', hassleExpr:'worried',
            text: "I have been hiding ever since. I am afraid they will come back." },
          { side:'hassel', speaker:'Hassel', hassleExpr:'determined',
            text: "You're safe now. I'm not here to take anything. I'm here to listen." },
          { side:'thought', speaker:'Hassel', hassleExpr:'thinking',
            text: "The octopus saw everything. It watched the machines descend, heard the grinding, felt the coral's pain. What else is hiding in the deep, too afraid to speak?" },
        ],
        clue: { title: 'Octopus Testimony', text: 'Underwater Extraction + Machine Sounds' },
        expression: 'worried',
      },
      {
        id: 'coral', name: 'Coral',
        sheetKey: 'coral',
        movType: 'static',
        useStaticSprite: true,
        x: 0, y: 0,
        fixedReefPlacement: true,
        patrolRadius: 0, speed: 0,
        solid: true,
        dialogue: [
          { side:'hassel', speaker:'Hassel', hassleExpr:'sad',
            text: "You were so beautiful once. I can feel it. I can feel what you lost." },
          { side:'npc', speaker:'Coral', hassleExpr:'sad',
            text: "I was beautiful once. I was home to thousands. Fish, crabs, turtles. They lived in my branches. I was alive. I breathed. I grew. I sheltered." },
          { side:'npc', speaker:'Coral', hassleExpr:'sad',
            text: "Then the heat came. I couldn't breathe. My color drained away. I turned white." },
          { side:'hassel', speaker:'Hassel', hassleExpr:'worried',
            text: "You're not dead. You're waiting. I can feel it." },
          { side:'npc', speaker:'Coral', hassleExpr:'idle',
            text: "Yes. I am waiting. Waiting for the heat to go away. Waiting for the water to cool. I remember what it was like to be alive. I miss it." },
          { side:'hassel', speaker:'Hassel', hassleExpr:'determined',
            text: "I will remember you. I will tell the world that you are still here, waiting." },
          { side:'npc', speaker:'Coral', hassleExpr:'idle',
            text: "That is all I ask. That someone remembers. That someone cares enough to wait with me." },
          { side:'thought', speaker:'Hassel', hassleExpr:'thinking',
            text: "The coral is not dead. It is waiting. Frozen in time, holding a memory of what it was. How long can they wait?" },
        ],
        clue: { title: 'Coral Memory', text: 'Coral Bleaching + Ecosystem Collapse' },
        expression: 'sad',
      },
      {
        id: 'whale', name: 'Whale',
        sheetKey: 'whale',
        movType: 'loop', loopDir: 1,
        yMin: 0.28, yMax: 0.62,
        x: -600, y: 0, patrolRadius: 0, speed: 0.6,
        solid: false,
        dialogue: [
          { side:'hassel', speaker:'Hassel (whispering)', hassleExpr:'sad',
            text: "You came all this way... to find me, didn't you?" },
          { side:'npc', speaker:'Whale', hassleExpr:'idle',
            text: "I sing, and no one answers. I search, and no one is found. I am the last of my pod. The last of my song." },
          { side:'npc', speaker:'Whale', hassleExpr:'idle',
            text: "I remember when the ocean was full of voices. My family. My friends. We sang together across the endless blue. Now... I sing alone." },
          { side:'npc', speaker:'Whale', hassleExpr:'idle',
            text: "The green light came from the sky. The heat rose. The coral died. The fish left. My pod left. I am the only one who stayed." },
          { side:'npc', speaker:'Whale', hassleExpr:'idle',
            text: "I don't know why I stay. Perhaps I am waiting. Waiting for the water to cool. Waiting for the voices to return. Waiting for a reason to sing again." },
          { side:'npc', speaker:'Whale', hassleExpr:'idle',
            text: "You are the first to listen in a long time. Thank you for hearing me." },
          { side:'hassel', speaker:'Hassel', hassleExpr:'sad',
            text: "I will always remember you. Your song will not die. I will carry it with me, wherever I go. You are not alone. Not while I remember." },
          { side:'npc', speaker:'Whale', hassleExpr:'idle',
            text: "Then I will swim a little longer. I will sing a little louder. And I will wait for the day when the water is cool again, and the voices return." },
          { side:'npc', speaker:'Whale', hassleExpr:'idle',
            text: "Farewell, little one. May your journey bring you peace." },
          { side:'thought', speaker:'Hassel', hassleExpr:'thinking',
            text: "A whale's song carries across oceans. But when no one is left to answer, the song becomes a lament. This whale is the last of its kind. Its song is a memorial." },
        ],
        clue: { title: 'Whale Testimony', text: 'Ecosystem Collapse + Loss of Biodiversity + Alien Presence' },
        expression: 'sad',
      },
    ],
    garden: [
      {
        id: 'butterfly', name: 'Butterfly',
        sheetKey: 'butterfly',
        // Brown wave — gentle wide sine across full screen, mid height
        movType: 'loop', loopDir: 1,
        yMin: 0.28, yMax: 0.46,
        zigzag: true, zigzagSpeed: 0.032,
        x: -200, y: 0, patrolRadius: 0, speed: 0.9,
        dialogue: [
          { side:'hassel', speaker:'Hassel', hassleExpr:'sad',
            text: "You're still here. You're still fighting. I can see how tired you are." },
          { side:'npc', speaker:'Butterfly', hassleExpr:'sad',
            text: "I remember when the garden was full of flowers — real flowers, the ones I could rest on. I remember the scent of nectar. I remember the joy of dancing in the sun with others. There were so many of us. We painted the air with color." },
          { side:'npc', speaker:'Butterfly', hassleExpr:'sad',
            text: "Then the flowers changed. The ones I needed were gone. Replaced by beauty that fed no one. I kept flying, searching for a place to rest, a flower to feed on. I never found one." },
          { side:'npc', speaker:'Butterfly', hassleExpr:'sad',
            text: "I grew tired. I couldn't fly anymore. I fell. And then I saw the green light from the sky. I don't know what it was. I only know it brought the silence." },
          { side:'hassel', speaker:'Hassel', hassleExpr:'sad',
            text: "You're the last one, aren't you? The last butterfly in this garden." },
          { side:'npc', speaker:'Butterfly', hassleExpr:'sad',
            text: "Yes. The others left. Or they died. I don't know which. I stayed because this was my home. I couldn't leave. Even when there was nothing left to stay for. I miss the others. I miss dancing with them. I miss the joy." },
          { side:'hassel', speaker:'Hassel', hassleExpr:'worried',
            text: "I will remember you. I will remember the dance. I will remember the color you brought to this world." },
          { side:'npc', speaker:'Butterfly', hassleExpr:'idle',
            text: "Then I will not be forgotten. Thank you, little one. I am so tired. But I am glad you came. I am glad someone remembers. Tell them... we were beautiful once. Tell them we danced." },
          { side:'hassel', speaker:'Hassel', hassleExpr:'determined',
            text: "I will. I promise. You were beautiful. You still are." },
          { side:'thought', speaker:'Hassel', hassleExpr:'thinking',
            text: "A single butterfly remembers a garden full of dancers. It remembers the joy, the color, the life. And now it is alone — the last of its kind, fluttering weakly, waiting to join the others. How many other gardens have one last butterfly, dancing alone, remembering what was lost?" },
        ],
        clue: { title: 'Butterfly Memory', text: 'Native Flower Loss + Pollinator Collapse + Alien Presence' },
        expression: 'sad',
      },
      {
        id: 'robin', name: 'Robin',
        sheetKey: 'robin',
        // Yellow wave — gentle sine across upper screen, flies left to right
        movType: 'loop', loopDir: 1,
        yMin: 0.06, yMax: 0.28,
        zigzag: true, zigzagSpeed: 0.045,
        x: -200, y: 0, patrolRadius: 0, speed: 2.2,
        solid: false,
        dialogue: [
          { side:'hassel', speaker:'Hassel', hassleExpr:'sad',
            text: "You're the only bird I've seen here. You must be so lonely." },
          { side:'npc', speaker:'Robin', hassleExpr:'sad',
            text: "I remember the insects. There were so many. I would sing and eat all day. The garden was full of life — buzzing, chirping, rustling. I had a family. We built a nest together. We sang together." },
          { side:'npc', speaker:'Robin', hassleExpr:'sad',
            text: "Then the insects began to disappear. I had to fly further to find food. I sang less. My songs grew quieter. My family left. They flew away to find food elsewhere. I stayed. I stayed because this was my home." },
          { side:'hassel', speaker:'Hassel', hassleExpr:'sad',
            text: "You're the last bird here. You sing alone." },
          { side:'npc', speaker:'Robin', hassleExpr:'idle',
            text: "Yes. I sing alone. I sing for the ones who left. I sing for the insects that vanished. I sing for the garden that died. I sing because if I stop, there will be no sound at all." },
          { side:'npc', speaker:'Robin', hassleExpr:'idle',
            text: "I heard a sound — a deep hum from underground. And I saw the green light. I don't know what happened. I only know the garden died, and I am the only one left to remember it." },
          { side:'hassel', speaker:'Hassel', hassleExpr:'determined',
            text: "You are not alone. I am here now. I will remember with you." },
          { side:'npc', speaker:'Robin', hassleExpr:'idle',
            text: "Thank you. I have not had anyone to sing with in a long time. Will you stay with me? Just for a little while?" },
          { side:'hassel', speaker:'Hassel', hassleExpr:'happy',
            text: "I will stay. I will listen to your song." },
          { side:'thought', speaker:'Hassel', hassleExpr:'thinking',
            text: "A robin sings alone in a silent garden. It sings for the ones who left, for the insects that vanished, for the life that faded. It sings because silence is worse than singing alone. It sings because remembering is all it has left." },
        ],
        clue: { title: 'Robin Memory', text: 'Insect Population Decline + Ecosystem Collapse + Alien Presence' },
        expression: 'sad',
      },
      {
        id: 'daisy', name: 'Daisy',
        sheetKey: 'daisy',
        movType: 'static',
        useStaticSprite: true,
        xFrac: 0.46, yFrac: 0.90, patrolRadius: 0, speed: 0,
        solid: true,
        dialogue: [
          { side:'hassel', speaker:'Hassel', hassleExpr:'sad',
            text: "You're still here. The last of your kind, hiding in this corner. You haven't given up." },
          { side:'npc', speaker:'Daisy', hassleExpr:'sad',
            text: "We were here first. We grew tall and proud. We fed the bees, the butterflies, the birds. We were the heart of the garden." },
          { side:'npc', speaker:'Daisy', hassleExpr:'sad',
            text: "Then they came — the ornamental plants. Beautiful, large, bright. They pushed us out. They replaced us. We were forgotten. We were left to wither in this corner." },
          { side:'npc', speaker:'Daisy', hassleExpr:'sad',
            text: "And then the green light appeared. The garden fell silent. The bees stopped coming. The birds stopped singing. We are the last of our kind. And soon, we will be gone too." },
          { side:'hassel', speaker:'Hassel', hassleExpr:'worried',
            text: "You are not gone yet. You are still here. You are still blooming." },
          { side:'npc', speaker:'Daisy', hassleExpr:'idle',
            text: "We bloom because it is all we know. We bloom because we remember what it was like to be part of something beautiful. We bloom because we hope — hope that someone will remember us. Will you remember us?" },
          { side:'hassel', speaker:'Hassel', hassleExpr:'determined',
            text: "I will. I will remember your petals, your color, your hope. I will tell the world that you were here — that you bloomed even when everything around you died." },
          { side:'npc', speaker:'Daisy', hassleExpr:'idle',
            text: "Then we will not be forgotten. Thank you, little one. We were beautiful once. We were the heart of the garden. And we are grateful that someone remembered." },
          { side:'thought', speaker:'Hassel', hassleExpr:'thinking',
            text: "A handful of daisies, tucked away in a forgotten corner, blooming in defiance. They know they are dying. They know they are the last. But they bloom anyway. Because blooming is all they know. Because hope is all they have." },
        ],
        clue: { title: "Daisy's Memory", text: 'Native Flowers Removed + Replaced with Ornamentals' },
        expression: 'sad',
      },
      {
        id: 'oak_tree', name: 'Oak Tree',
        sheetKey: 'oak_tree',
        movType: 'static',
        xFrac: 0.88, yFrac: 0.82, patrolRadius: 0, speed: 0,
        solid: true,
        dialogue: [
          { side:'hassel', speaker:'Hassel', hassleExpr:'idle',
            text: "You've been here for centuries. You've seen it all. You remember everything." },
          { side:'npc', speaker:'Oak Tree', hassleExpr:'idle',
            text: "I have stood here for three hundred years. I have seen the garden change — season by season, year by year. I have seen the native flowers replaced with ornamentals. I have seen the bees dwindle, the butterflies vanish, the birds grow silent." },
          { side:'npc', speaker:'Oak Tree', hassleExpr:'idle',
            text: "It happened slowly. So slowly that most did not notice. A flower here. A bee there. A bird gone. Each season, a little less life. Each year, a little more silence." },
          { side:'npc', speaker:'Oak Tree', hassleExpr:'idle',
            text: "And then came the green light. The aliens. They took something from the soil. After that, the garden grew silent. The birds stopped singing. The flowers stopped blooming. Even I can feel it — the land is losing its strength." },
          { side:'hassel', speaker:'Hassel', hassleExpr:'sad',
            text: "You carry the memory of three centuries. You watched the garden die, season by season. That must be so heavy." },
          { side:'npc', speaker:'Oak Tree', hassleExpr:'idle',
            text: "It is. But I carry it so that the garden is not forgotten. I carry the memory of the bees, the butterflies, the birds, the flowers. When I fall, that memory will fall with me. Unless someone carries it forward. Will you carry it, little one?" },
          { side:'hassel', speaker:'Hassel', hassleExpr:'determined',
            text: "I will. I will carry the memory of the garden. I will carry the memory of the bees, the butterflies, the birds, the flowers. I will carry it all. You have stood for three hundred years. And now, I will remember with you." },
          { side:'npc', speaker:'Oak Tree', hassleExpr:'idle',
            text: "Then I will not be forgotten. I have stood for three hundred years — and I am grateful that someone will remember me when I fall. The land remembers. The garden remembers. And now, so do you." },
          { side:'thought', speaker:'Hassel', hassleExpr:'thinking',
            text: "An oak tree remembers three centuries of change. It watched the garden die, one season at a time. It tried to warn the others, but they could not see the long decline. Now it stands alone — the last witness to a world that no longer exists." },
        ],
        clue: { title: 'Oak Tree Memory', text: 'Long-Term Ecosystem Decline + Soil Depletion + Alien Energy Signature' },
        expression: 'determined',
      },
      {
        id: 'mushroom', name: 'Mushroom',
        sheetKey: 'mushroom',
        movType: 'static',
        useStaticSprite: true,
        xFrac: 0.90, yFrac: 0.91, patrolRadius: 0, speed: 0,
        solid: true,
        dialogue: [
          { side:'hassel', speaker:'Hassel', hassleExpr:'worried',
            text: "You're still here, clinging to the soil. But the ground around you feels so dead." },
          { side:'npc', speaker:'Mushroom', hassleExpr:'worried',
            text: "I was alive once. I held the plants together. I fed the world beneath the surface. Thousands of roots connected through me. I was the web of life beneath this garden." },
          { side:'npc', speaker:'Mushroom', hassleExpr:'worried',
            text: "But they came with their chemicals. They burned me. They drained me with their machines. I felt it drain away. Everything I was... everything I connected... gone." },
          { side:'npc', speaker:'Mushroom', hassleExpr:'worried',
            text: "Now I am just dust. Nothing grows here anymore. The roots have no one to talk to. The soil has no memory left." },
          { side:'hassel', speaker:'Hassel', hassleExpr:'sad',
            text: "You were the heart of the soil. And they destroyed you without even seeing you." },
          { side:'thought', speaker:'Hassel', hassleExpr:'thinking',
            text: "The mushroom was the invisible network beneath everything — the web of life connecting tree to flower to bee. When the chemicals came, they didn't just kill a plant. They severed the garden's memory." },
        ],
        clue: { title: 'Mushroom Memory', text: 'Soil Depletion + Chemical Contamination + Network Collapse' },
        expression: 'worried',
      },
    ],
  },

  objects: {
    ocean: [
      {
        id: 'net', name: 'Broken Fishing Net',
        src: 'assests/objects/Story 1/net.png', w: 130, h: 150,
        xFrac: 0.52, yFrac: 0.88, solid: true, thoughtOnly: true,
        dialogue: [
          { side:'thought', speaker:'Hassel', hassleExpr:'worried',
            text: "This was cast to catch fish. But it caught more than fish — turtles, dolphins, coral. It was abandoned when it broke." },
          { side:'thought', speaker:'Hassel', hassleExpr:'thinking',
            text: "It doesn't stop. It never stops. It's a ghost that keeps hunting. Made by human hands. And it will never stop killing." },
        ],
        clue: { title: 'Broken Fishing Net', text: 'Ghost Fishing + Marine Life Death' },
      },
      {
        id: 'bottle', name: 'Plastic Bottle',
        src: 'assests/objects/Story 1/bottle.png', w: 70, h: 90,
        xFrac: 0.62, yFrac: 0.38, solid: false, static: true, thoughtOnly: true,
        dialogue: [
          { side:'thought', speaker:'Hassel', hassleExpr:'worried',
            text: "You were thrown away years ago. You floated across oceans. You were mistaken for food. You choked the life out of fish, birds, turtles." },
          { side:'thought', speaker:'Hassel', hassleExpr:'thinking',
            text: "You are immortal. You will never break down. You will haunt the ocean forever. A ghost of human convenience." },
        ],
        clue: { title: 'Plastic Bottle', text: 'Ocean Pollution + Microplastics' },
      },
      {
        id: 'anchor', name: 'Rusted Anchor',
        src: 'assests/objects/Story 1/anchor.png', w: 100, h: 120,
        xFrac: 0.40, yFrac: 0.90, solid: true, thoughtOnly: true,
        dialogue: [
          { side:'thought', speaker:'Hassel', hassleExpr:'determined',
            text: "You were dropped by a ship that came here to take. I can feel it. They left you behind when they fled with what they'd stolen." },
          { side:'thought', speaker:'Hassel', hassleExpr:'thinking',
            text: "A monument to greed. A rusting tombstone for the reef it helped destroy." },
        ],
        clue: { title: 'Rusted Anchor', text: 'Evidence of Underwater Extraction' },
      },
      {
        id: 'dead_coral', name: 'Dead Coral',
        src: 'assests/objects/Story 1/dead coral.png', w: 100, h: 125,
        xFrac: 0.63, yFrac: 0.90, solid: true, thoughtOnly: true,
        dialogue: [
          { side:'thought', speaker:'Hassel', hassleExpr:'sad',
            text: "You were part of something beautiful once. Thousands of lives depended on you. You were the foundation of an entire world." },
          { side:'thought', speaker:'Hassel', hassleExpr:'thinking',
            text: "The coral doesn't scream. It doesn't rage. It simply fades — color draining, life leaving, until only white bone remains. The quietest extinction." },
        ],
        clue: { title: 'Bleached Coral', text: 'Coral Bleaching + Ocean Acidification' },
      },
      {
        id: 'buoy', name: 'Temperature Buoy',
        src: 'assests/objects/Story 1/ocean_temperature_bouy.png', w: 75, h: 115,
        xFrac: 0.83, yFrac: 0.48, isFinal: true, solid: false, static: true, thoughtOnly: true,
        dialogue: [
          { side:'thought', speaker:'Hassel', hassleExpr:'shock',
            text: "The data is undeniable. The ocean temperature has risen steadily for decades. And these heat spikes... they coincide exactly with the green light." },
          { side:'thought', speaker:'Hassel', hassleExpr:'determined',
            text: "The ocean is burning. The reef is dying. The aliens accelerated what humans started. And this little buoy has been recording it all, faithfully, alone." },
        ],
        clue: { title: '⚠ FINAL CLUE — Temperature Buoy', text: 'Ocean Temperature Rising + Alien Energy Signature Detected' },
      },
    ],
    garden: [
      {
        id: 'statue', name: 'Garden Statue',
        src: 'assests/objects/Story 2/statue.png', w: 120, h: 230,
        xFrac: 0.09, yFrac: 0.91, solid: true, thoughtOnly: true,
        dialogue: [
          { side:'thought', speaker:'Hassel', hassleExpr:'thinking',
            text: "You have stood here for centuries. You watched children play, lovers whisper, gardeners tend the flowers. You watched the native flowers disappear, the bees dwindle, the butterflies vanish, the birds grow silent." },
          { side:'thought', speaker:'Hassel', hassleExpr:'sad',
            text: "You are a silent witness to the garden's death. You remember the laughter, the joy, the life. Now there is only silence. But you are still here. You are still watching. You are still remembering. And I will remember with you." },
        ],
        clue: { title: 'Garden Statue', text: 'Long-Term Witness to Ecosystem Change' },
      },
      {
        id: 'flower_bed', name: 'Flower Bed',
        src: 'assests/objects/Story 2/flower_bed.png', w: 140, h: 108,
        xFrac: 0.22, yFrac: 0.93, solid: true, thoughtOnly: true,
        dialogue: [
          { side:'thought', speaker:'Hassel', hassleExpr:'sad',
            text: "You were planted with care. You were watered, fed, and loved. But the soil changed. The nutrients were drained. You could not grow as you should. You withered." },
          { side:'thought', speaker:'Hassel', hassleExpr:'thinking',
            text: "You are not sick — you are starved. The land has no life left to give. The flowers that grew here once are gone. The seeds that fell here will never sprout. But I remember the flowers that grew here. And I will not let that memory die." },
        ],
        clue: { title: 'Flower Bed', text: 'Soil Depletion + Nutrient Loss' },
      },
      {
        id: 'rock', name: 'Ancient Rock',
        src: 'assests/objects/Story 2/rock.png', w: 130, h: 110,
        xFrac: 0.75, yFrac: 0.93, solid: true, thoughtOnly: true,
        dialogue: [
          { side:'thought', speaker:'Hassel', hassleExpr:'thinking',
            text: "You have been here since the garden was created. You have felt the rain, the sun, the wind. You have felt the earth change. Something was taken — something deep beneath the surface. You felt it. You remember it. Even though you cannot speak, you carry the memory of what happened." },
          { side:'thought', speaker:'Hassel', hassleExpr:'determined',
            text: "A rock that cannot speak still carries the memory of what was taken. And now, so do I." },
        ],
        clue: { title: 'Ancient Rock', text: 'Underground Energy Drain + Alien Extraction' },
      },
      {
        id: 'branch', name: 'Dried Branch',
        src: 'assests/objects/Story 2/branch.png', w: 110, h: 90,
        xFrac: 0.65, yFrac: 0.91, solid: true, thoughtOnly: true,
        dialogue: [
          { side:'thought', speaker:'Hassel', hassleExpr:'sad',
            text: "You were part of something living once. You were connected to the tree, to the soil, to the life of the garden. Then you were cut off — left to dry and die. You are brittle. You are broken. You are what remains when life leaves the land." },
          { side:'thought', speaker:'Hassel', hassleExpr:'thinking',
            text: "A branch that once held leaves, that once carried life, now crumbles to dust. It is a reminder that life is fragile — that everything living will one day return to the earth. But even in death, it carries the memory of what it was. It will not be forgotten." },
        ],
        clue: { title: 'Dried Branch', text: 'Deforestation + Ecosystem Collapse' },
      },
      {
        id: 'nest', name: 'Empty Bird Nest',
        src: 'assests/objects/Story 2/nest.png', w: 110, h: 110,
        xFrac: 0.84, yFrac: 0.38, isFinal: true, solid: false, thoughtOnly: true,
        dialogue: [
          { side:'thought', speaker:'Hassel', hassleExpr:'sad',
            text: "You were built with care. Woven from twigs and grass and love. You held eggs — new life, new hope. The parents sang to you. They kept you warm. But then the insects disappeared. There was no food. The parents flew away and never returned." },
          { side:'thought', speaker:'Hassel', hassleExpr:'thinking',
            text: "You are empty. You hold only memories of what could have been. A nest without birds. A home without life. But I will remember you. I will remember the eggs that never hatched, the songs that were never sung. You were a home once. And you will not be forgotten." },
        ],
        clue: { title: '⚠ FINAL CLUE — Empty Bird Nest', text: 'Ecosystem Collapse + Alien Presence Detected' },
      },
    ],
  },

  // Investigation connections
  // Format: [idA, idB, hintText]
  connections: {
    ocean: [
      ['clownfish',  'coral',
        'Both the Clownfish and the Coral lived in the same reef. The clownfish lost its home when the coral bleached. They share the same cause — rising heat.'],
      ['coral',      'dead_coral',
        'The living Coral and the Dead Coral tell the same story from different stages. One is fading, the other already gone. Bleaching connects them.'],
      ['sea_turtle', 'octopus',
        'The Sea Turtle and the Octopus both witnessed the alien machines descend into the ocean depths. They are the only two eyewitnesses.'],
      ['octopus',    'anchor',
        'The Octopus heard a grinding sound and saw the extraction machines. The Rusted Anchor is physical evidence left behind by those same machines.'],
      ['whale',      'bottle',
        'The Whale spoke of a dying ocean full of pollution and lost life. The Plastic Bottle is a symbol of that exact human pollution killing marine creatures.'],
      ['buoy',       'sea_turtle',
        'The Temperature Buoy recorded ocean heat rising over decades. The Sea Turtle lived through all of those decades and felt every degree of change.'],
    ],
    garden: [
      ['butterfly',  'flower_bed',
        'The Butterfly needed native flowers to survive. The Flower Bed shows soil so depleted it can no longer support the plants that pollinators depend on.'],
      ['daisy',      'butterfly',
        'The Daisy was pushed out by ornamental plants, leaving pollinators with nothing. The Butterfly lost its food source when native flowers like the daisy disappeared.'],
      ['robin',      'nest',
        'The Robin built that nest and then abandoned it when insects vanished. The Empty Nest is the direct result of the insect collapse the Robin described.'],
      ['oak_tree',   'rock',
        'The Oak Tree felt energy draining from the soil over centuries. The Ancient Rock also records that underground drain — something was taken from deep below.'],
      ['mushroom',   'branch',
        'The Mushroom described soil killed by chemicals. The Dried Branch is the result — when the soil dies, the trees connected to it die too.'],
      ['oak_tree',   'statue',
        'Both the Oak Tree and the Garden Statue have stood for centuries, silently witnessing the slow death of the garden. They share three hundred years of memory.'],
    ],
  },
};
